# version: "3.8"

services:
  backend:
    container_name: GribTripBackend
    build:
      context: ./GribTripBackend
      dockerfile: Dockerfile
    environment:
      API_HOST: 0.0.0.0
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ACCESS_TOKEN_LT: ${ACCESS_TOKEN_LT}
      REFRESH_TOKEN_LT: ${REFRESH_TOKEN_LT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ENCRYPT_ALG: ${ENCRYPT_ALG}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - backend

  db:
    image: postgres:17
    container_name: GribTripDB
    build:
      context: ./GribTripBackend
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: GribTripFrontend
    build:
      context: ./GribTripFrontend
      dockerfile: Dockerfile
    env_file:
      - ./GribTripFrontend/.env
    environment:
      VITE_API_URL: http://localhost/api/
      HOST: 0.0.0.0
      PORT: 5173
    depends_on:
      - backend
    networks:
      - default


  nginx:
   image: nginx:1.27-alpine
   ports:
     - "80:80"
   depends_on:
     - frontend
     - backend
   networks:
     - default
   volumes:
     - "./nginx.conf:/etc/nginx/nginx.conf"

volumes:
  postgres_data:

networks:
  default:
  backend: